# Generated by Django 2.2.6 on 2019-10-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('edit', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
