# Generated by Django 2.2.6 on 2019-10-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='text',
            field=models.TextField(default='ttt'),
            preserve_default=False,
        ),
    ]
