# Generated by Django 2.2.6 on 2019-10-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_mymodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemLI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
