# Generated by Django 2.2.6 on 2019-10-15 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_auto_20191010_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemli',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
