# Generated by Django 2.2.6 on 2019-10-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_itemli_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemli',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='itemli',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemli',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
